services:
  # Rails Backend API
  - type: web
    name: garage-management-backend
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails server -p $PORT -b 0.0.0.0
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: garage-management-db
          property: connectionString
    databases:
      - name: garage-management-db
        databaseName: garage_management_production
        user: garage_management_user

  # React Frontend
  - type: web
    name: garage-management-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://garage-management-backend.onrender.com 